### ISSUE TITLE
Applications vs Plugins (Semantics)

### ISSUE THREAD

**Issue by JRJurman** [mea-ola/process#23]
Right now, the services that run with the same server data are tentatively titled "Plugins". This includes the arena, and any other services that up until this point have been referred to as microservices...

**Comment by 7imbrook** [comment]
Citing [Plugin](https://en.wikipedia.org/wiki/Plug-in_%28computing%29) on wikipedia. I feel like it's the most descriptive of what we want, and doesn't get confused with the service/infrastructure naming of things.

**Comment by kristenmills** [comment]
I mean by definition, it is a plugin

> In computing, a plug-in (or add-in / addin, plugin, extension or add-on / addon) is a software component that adds a specific feature to an existing software application.

Wikipedia told me that.

**Comment by kristenmills** [comment]
Damnit timbrook. Beating me to it

**Comment by JRJurman** [comment]
@kristenmills and I have discussed and agree that maybe the more apt term would be applications, considering that these (in general) are separate application that just run on the same pool of data, not something that is obvious in the main-extension view.
