### ISSUE TITLE
Breeding

### ISSUE THREAD

**Issue by JRJurman** [mea-ola/process#7]
The idea of creating new pets that inherit properties of the two friends' pets.

**Comment by evajurman** [comment]
- you should only be able to breed once per pet.
- there should be an tree of your parents, grandparents, etc... so people can see the progression of breeding
- when breeding, one pet is issued to you, your friend, and is available as an egg to be found randomly by a random user.

**Comment by JRJurman** [comment]
Do people just randomly pick up eggs? I think I would get annoyed if I just grabbed somebody's random egg... (Regardless if it was one of my friend's egg's or not)...

That being said, getting eggs from other friends' pets might be... neat?

**Comment by kristenmills** [comment]
I think you should be able to reject the egg if you don't want it. My understanding was that you could find the egg and then chose whether you wanted it or not. I mean ultimately if you don't want a pet, you should be able to get rid of it so even if we forced it upon the user, they could just get rid of it if they don't like it.

**Comment by JRJurman** [comment]
I just don't want a bunch of random eggs popping up in my extension... Maybe it would suffice to have this be a microservice? Both breeding and finding eggs?

Kinda like the day care for Pokemon...

**Comment by kristenmills** [comment]
Idk. I don't think you should have to opt in to breeding. Eggs though, we can have a setting that says I don't want to find eggs. And then we won't give those users eggs.

**Comment by evajurman** [comment]
Just like there is an icon when your pet is hungry, sometimes when you land on a page, you find an egg. if you move away from that page, then the egg is lost. when you click the icon, you have an option to pick the egg up. would something like that work?

**Comment by evajurman** [comment]
(the cool part would be seeing how the generations overlapped; imagine seeing an egg whose time line was related to an old pet you had)
